openshift_cluster_content:
  - object: Dashboards - DevOps
    content:
      - name: Software Delivery Metrics Dashboard
        file: "{{ inventory_dir }}/../dashboard-sdm.yml"
        namespace: "openshift-monitoring"
        tags:
          - dashboard-sdm
      - name: Mount Software Delivery Dashboard to Grafana
        action: patch
        file: "{{ inventory_dir }}/../grafana-deployment.yml"
        params: "{{ inventory_dir }}/../sdm-volume-patch.yml"
        namespace: "openshift-monitoring"
        tags:
          - dashboard-sdm
