apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: gitea-server
objects:
  - apiVersion: gpte.opentlc.com/v1alpha1
    kind: Gitea
    metadata:
      name: gitea-server
    spec:
      postgresqlVolumeSize: "${POSTGRESQL_VOLUME_SIZE}"
      giteaVolumeSize: "${GITEA_VOLUME_SIZE}"
      giteaSsl: ${GITEA_SSL}
parameters:
- name: POSTGRESQL_VOLUME_SIZE
- name: GITEA_VOLUME_SIZE
- name: GITEA_SSL