k8s_namespace: hygieia
gitea_postgresql_pv_size: 1Gi
gitea_pv_size: 1Gi

openshift_cluster_content:
  - object: Gitea Components
    content:
    - name: Gitea Deployment
      template: "{{ inventory_dir }}/../../dependencies/docker-openshift-gitea/openshift/gitea-persistent-template.yaml"
      namespace: "{{ k8s_namespace }}"
      params_from_vars:
        DB_VOLUME_CAPACITY: "{{ gitea_postgresql_pv_size }}"
        GITEA_VOLUME_CAPACITY: "{{ gitea_pv_size }}"
        HOSTNAME: "gitea.{{ k8s_namespace }}.{{ openshift_default_subdomain }}"
      action: create