- hosts: localhost
  connection: local
  vars_files:
    - ../vars/mdt.yml
  tasks:
    - name: Downloading Git Dependencies
      git:
        repo: "{{ item.uri }}"
        version: "{{ item.branch }}"
        dest: "{{ playbook_dir }}/../dependencies/{{ item.name }}"
      loop: "{{ mdt_git_repositories }}"
    