name: Chart Lint
on:
  push:
    branches: [ master ]
    paths: 
      - 'charts/**'
      - 'lintconf.yaml'
      - '.github/workflows/chart-lint.yml'
  pull_request:
    branches: [ master ]
    paths: 
      - 'charts/**'
      - 'lintconf.yaml'
      - '.github/workflows/chart-lint.yml'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
    
      - name: Install chart-testing tool `ct`
        uses: helm/chart-testing-action@v2.1.0
        with:
          version: "v3.4.0"
      
      - name: Lint charts
        run: ct lint --config ct.yaml
